name: Update Docker Hub Description
on:
  push:
    branches:
      - master
    paths:
      - README.MD
      - .github/workflows/DockerHub-Description.yml
jobs:
  dockerHubDescription:
    if: startsWith(github.repository, 'Binaryify/NeteaseCloudMusicApi')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@202973a37c8a723405c0c5f0a71b6d99db470dae # v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: binaryify/netease_cloud_music_api
        short-description: ${{ github.event.repository.description }}
        readme-filepath: ./README.MD
